name: test_dart_frog_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  json_annotation: ^4.9.0
  orm: ^3.4.8
  crypto: ^3.0.6
  dart_frog_auth: ^1.2.0
  dart_jsonwebtoken: ^2.14.2
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  shelf_multipart: 2.0.0
  mime: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
